# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17.0.1
          registry-url: https://npm.pkg.github.com/
          cache: "npm"
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PACKAGE_PAT}}
      - run: npm run build --if-present
        env:
          REACT_APP_MAILCHIMP_URL: ${{ secrets.REACT_APP_MAILCHIMP_URL }}
          REACT_APP_MAILCHIMP_U: ${{ secrets.REACT_APP_MAILCHIMP_U }}
          REACT_APP_MAILCHIMP_ID: ${{ secrets.REACT_APP_MAILCHIMP_ID }}
      - run: npm run test:cover
